name: Staging Deployment

on:
  push:
    branches: [ develop, staging ]
  workflow_dispatch:

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: https://idealase.github.io/staging
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run basic health checks
        run: |
          echo "Running basic validation..."
          test -f index.html || { echo "Error: index.html not found"; exit 1; }
          test -f manifest.json || { echo "Error: manifest.json not found"; exit 1; }
          echo "✅ Basic validation passed"
        
      - name: Setup Pages for staging
        uses: actions/configure-pages@v4
        
      - name: Upload staging artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to staging environment
        uses: actions/deploy-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}